PSPSDK = $(shell psp-config --pspsdk-path)
PSPLIBSDIR = $(PSPSDK)/..
TARGET = PSPVice

OBJS = 	src/alarm.o \
	src/attach.o \
	src/autostart.o \
	src/charset.o \
	src/clkguard.o \
	src/cmdline.o \
	src/cbmdos.o \
	src/cbmimage.o \
	src/color.o \
	src/crc32.o \
	src/datasette.o \
	src/debug.o \
	src/dma.o \
	src/emuid.o \
	src/event.o \
	src/findpath.o \
	src/fliplist.o \
	src/gcr.o \
	src/info.o \
	src/init.o \
	src/initcmdline.o \
	src/interrupt.o \
	src/ioutil.o \
	src/joystick.o \
	src/kbdbuf.o \
	src/keyboard.o \
	src/lib.o \
	src/log.o \
	src/machine-bus.o \
	src/machine.o \
	src/main.o \
	src/maincpu.o \
	src/mouse.o \
	src/network.o \
	src/palette.o \
	src/ram.o \
	src/rawfile.o \
	src/resources.o \
	src/romset.o \
	src/screenshot.o \
	src/snapshot.o \
	src/sound.o \
	src/sysfile.o \
	src/traps.o \
	src/translate.o \
	src/util.o \
	src/vsync.o \
	src/zfile.o \
	src/zipcode.o \
	src/c64/c64.o \
	src/c64/c64_256k.o \
	src/c64/c64acia1.o \
	src/c64/c64bus.o \
	src/c64/c64cia1.o \
	src/c64/c64cia2.o \
	src/c64/c64-cmdline-options.o \
	src/c64/c64datasette.o \
	src/c64/c64drive.o \
	src/c64/c64export.o \
	src/c64/c64fastiec.o \
	src/c64/c64iec.o \
	src/c64/c64io.o \
	src/c64/c64keyboard.o \
	src/c64/c64mem.o \
	src/c64/c64meminit.o \
	src/c64/c64memlimit.o \
	src/c64/c64memrom.o \
	src/c64/c64memsnapshot.o \
	src/c64/c64parallel.o \
	src/c64/c64pla.o \
	src/c64/c64printer.o \
	src/c64/c64-resources.o \
	src/c64/c64rom.o \
	src/c64/c64romset.o \
	src/c64/c64rsuser.o \
	src/c64/c64-snapshot.o \
	src/c64/c64sound.o \
	src/c64/c64tpi.o \
	src/c64/c64video.o \
	src/c64/digimax.o \
	src/c64/georam.o \
	src/c64/mmc64.o \
	src/c64/patchrom.o \
	src/c64/plus256k.o \
	src/c64/plus60k.o \
	src/c64/psid.o \
	src/c64/ramcart.o \
	src/c64/reloc65.o \
	src/c64/reu.o \
	src/c64/tfe.o \
	src/c64/cart/actionreplay.o \
	src/c64/cart/atomicpower.o \
	src/c64/cart/c64cart.o \
	src/c64/cart/c64cartmem.o \
	src/c64/cart/crt.o \
	src/c64/cart/epyxfastload.o \
	src/c64/cart/expert.o \
	src/c64/cart/final.o \
	src/c64/cart/generic.o \
	src/c64/cart/ide64.o \
	src/c64/cart/kcs.o \
	src/c64/cart/retroreplay.o \
	src/c64/cart/supergames.o \
	src/c64/cart/supersnapshot.o \
	src/c64/cart/zaxxon.o \
  src/c64/cart/comal80.o \
  src/c64/cart/magicformel.o \
  src/c64/cart/ross.o \
  src/c64/cart/stb.o \
	src/c64/cart/actionreplay3.o \
	src/c64/cart/delaep256.o \
	src/c64/cart/delaep64.o \
	src/c64/cart/delaep7x8.o \
	src/c64/cart/magicformel.o \
	src/c64/cart/mikroass.o \
	src/c64/cart/rexep256.o \
	src/c64/patchrom.o \
	src/c64/psid.o \
	src/c64/reloc65.o \
	src/c64/reu.o \
	src/c64/tfe.o \
	src/c64/c64export.o \
	src/c64/c64romset.o \
	src/c64/georam.o \
	src/c64/plus60k.o \
  src/c64/ramcart.o \
	src/core/ciacore.o \
	src/core/ciatimer.o \
	src/core/riotcore.o \
	src/core/tpicore.o \
	src/core/viacore.o \
	src/crtc/crtc.o \
	src/crtc/crtc-cmdline-options.o \
	src/crtc/crtc-draw.o \
	src/crtc/crtc-mem.o \
	src/crtc/crtc-resources.o \
	src/crtc/crtc-snapshot.o \
	src/diskimage/diskimage.o \
	src/diskimage/fsimage.o \
	src/diskimage/fsimage-check.o \
	src/diskimage/fsimage-create.o \
	src/diskimage/fsimage-gcr.o \
	src/diskimage/fsimage-probe.o \
	src/diskimage/realimage.o \
	src/drive/drive.o \
	src/drive/drive-check.o \
	src/drive/drive-cmdline-options.o \
	src/drive/drivecpu.o \
	src/drive/driveimage.o \
	src/drive/drivemem.o \
	src/drive/drive-overflow.o \
	src/drive/drive-resources.o \
	src/drive/driverom.o \
	src/drive/drive-snapshot.o \
	src/drive/drivesync.o \
	src/drive/drive-writeprotect.o \
	src/drive/iec/cia1571d.o \
	src/drive/iec/cia1581d.o \
	src/drive/iec/glue1571.o \
	src/drive/iec/iec.o \
	src/drive/iec/iec-cmdline-options.o \
	src/drive/iec/iec-resources.o \
	src/drive/iec/iecrom.o \
	src/drive/iec/memiec.o \
	src/drive/iec/via1d1541.o \
	src/drive/iec/wd1770.o \
	src/drive/iec/c64exp/iec-c64exp.o \
	src/drive/iec/c64exp/mc6821.o \
	src/drive/iec/c64exp/profdos.o \
	src/drive/iec/c64exp/c64exp-cmdline-options.o \
	src/drive/iec/c64exp/c64exp-resources.o \
	src/drive/iecieee/iecieee.o \
	src/drive/iecieee/via2d.o \
	src/drive/ieee/fdc.o \
	src/drive/ieee/ieee.o \
	src/drive/ieee/ieee-cmdline-options.o \
	src/drive/ieee/ieee-resources.o \
	src/drive/ieee/ieeerom.o \
	src/drive/ieee/memieee.o \
	src/drive/ieee/riot1d.o \
	src/drive/ieee/riot2d.o \
	src/drive/ieee/via1d2031.o \
	src/drive/rotation.o \
	src/drive/tcbm/glue1551.o \
	src/drive/tcbm/mem1551.o \
	src/drive/tcbm/tcbm.o \
	src/drive/tcbm/tcbm-cmdline-options.o \
	src/drive/tcbm/tcbm-resources.o \
	src/drive/tcbm/tcbmrom.o \
	src/drive/tcbm/tpid.o \
	src/fileio/cbmfile.o \
	src/fileio/fileio.o \
	src/fileio/p00.o \
	src/fsdevice/fsdevice.o \
	src/fsdevice/fsdevice-close.o \
	src/fsdevice/fsdevice-cmdline-options.o \
	src/fsdevice/fsdevice-flush.o \
	src/fsdevice/fsdevice-open.o \
	src/fsdevice/fsdevice-read.o \
	src/fsdevice/fsdevice-resources.o \
	src/fsdevice/fsdevice-write.o \
	src/gfxoutputdrv/bmpdrv.o \
	src/gfxoutputdrv/gfxoutput.o \
	src/gfxoutputdrv/iffdrv.o \
	src/gfxoutputdrv/pcxdrv.o \
	src/gfxoutputdrv/ppmdrv.o \
	src/imagecontents/diskcontents.o \
	src/imagecontents/diskcontents-block.o \
	src/imagecontents/diskcontents-iec.o \
	src/imagecontents/imagecontents.o \
	src/imagecontents/tapecontents.o \
	src/iecbus/iecbus.o \
	src/monitor/asm6502.o \
	src/monitor/asmz80.o \
	src/monitor/mon_assemble6502.o \
	src/monitor/mon_assemblez80.o \
	src/monitor/mon_breakpoint.o \
	src/monitor/mon_command.o \
	src/monitor/mon_disassemble.o \
	src/monitor/mon_drive.o \
	src/monitor/mon_file.o \
	src/monitor/mon_lex.o \
	src/monitor/mon_memory.o \
	src/monitor/mon_parse.o \
	src/monitor/mon_register6502.o \
	src/monitor/mon_registerz80.o \
	src/monitor/mon_ui.o \
	src/monitor/mon_util.o \
	src/monitor/monitor.o \
	src/parallel/parallel.o \
	src/parallel/parallel-trap.o \
	src/plus4/plus4tcbm.o \
	src/printerdrv/driver-select.o \
	src/printerdrv/drv-ascii.o \
	src/printerdrv/drv-mps803.o \
	src/printerdrv/drv-nl10.o \
	src/printerdrv/interface-serial.o \
	src/printerdrv/interface-userport.o \
	src/printerdrv/output-graphics.o \
	src/printerdrv/output-select.o \
	src/printerdrv/output-text.o \
	src/printerdrv/printer.o \
	src/printerdrv/printer-serial.o \
	src/printerdrv/printer-userport.o \
	src/raster/raster.o \
	src/raster/raster-cache.o \
	src/raster/raster-canvas.o \
	src/raster/raster-changes.o \
	src/raster/raster-cmdline-options.o \
	src/raster/raster-line.o \
	src/raster/raster-line-changes.o \
	src/raster/raster-line-changes-sprite.o \
	src/raster/raster-modes.o \
	src/raster/raster-resources.o \
	src/raster/raster-sprite.o \
	src/raster/raster-sprite-cache.o \
	src/raster/raster-sprite-status.o \
	src/rs232drv/rs232drv.o \
	src/rs232drv/rsuser.o \
	src/serial/fsdrive.o \
	src/serial/serial.o \
	src/serial/serial-device.o \
	src/serial/serial-iec.o \
	src/serial/serial-iec-bus.o \
	src/serial/serial-iec-device.o \
	src/serial/serial-iec-lib.o \
	src/serial/serial-realdevice.o \
	src/serial/serial-trap.o \
	src/sid/fastsid.o \
	src/sid/sid.o \
	src/sid/sid-cmdline-options.o \
	src/sid/sid-resources.o \
	src/sid/sid-snapshot.o \
	src/sounddrv/sounddummy.o \
	src/sounddrv/sounddump.o \
	src/sounddrv/soundfs.o \
	src/sounddrv/soundpsp.o \
	src/sounddrv/soundspeed.o \
	src/sounddrv/soundwav.o \
	src/sounddrv/soundaiff.o \
	src/sounddrv/soundiff.o \
	src/sounddrv/soundvoc.o \
	src/tape/t64.o \
	src/tape/tap.o \
	src/tape/tape.o \
	src/tape/tapeimage.o \
	src/tape/tape-internal.o \
	src/tape/tape-snapshot.o \
	src/vdc/vdc.o \
	src/vdc/vdc-cmdline-options.o \
	src/vdc/vdc-draw.o \
	src/vdc/vdc-mem.o \
	src/vdc/vdc-resources.o \
	src/vdc/vdc-snapshot.o \
	src/vdrive/vdrive.o \
	src/vdrive/vdrive-command.o \
	src/vdrive/vdrive-bam.o \
	src/vdrive/vdrive-dir.o \
	src/vdrive/vdrive-iec.o \
	src/vdrive/vdrive-internal.o \
	src/vdrive/vdrive-rel.o \
	src/vdrive/vdrive-snapshot.o \
	src/vicii/vicii.o \
	src/vicii/vicii-badline.o \
	src/vicii/vicii-cmdline-options.o \
	src/vicii/vicii-color.o \
	src/vicii/vicii-draw.o \
	src/vicii/vicii-fetch.o \
	src/vicii/vicii-irq.o \
	src/vicii/vicii-mem.o \
	src/vicii/vicii-phi1.o \
	src/vicii/vicii-resources.o \
	src/vicii/vicii-snapshot.o \
	src/vicii/vicii-sprites.o \
	src/vicii/vicii-timing.o \
	src/video/render1x1.o \
	src/video/render1x1pal.o \
	src/video/render1x2.o \
	src/video/render2x2.o \
	src/video/render2x2pal.o \
	src/video/renderscale2x.o \
	src/video/renderyuv.o \
	src/video/video-canvas.o \
	src/video/video-cmdline-options.o \
	src/video/video-color.o \
	src/video/video-render.o \
	src/video/video-render-1x2.o \
	src/video/video-render-2x2.o \
	src/video/video-render-pal.o \
	src/video/video-resources.o \
	src/video/video-resources-pal.o \
	src/video/video-viewport.o \
	src/arch/psp/FontC64.o \
  src/arch/psp/gr_button_PSP.o \
  src/arch/psp/archdep.o \
  src/arch/psp/bitmap.o \
  src/arch/psp/c64kbd.o \
  src/arch/psp/c64ui.o \
  src/arch/psp/console.o \
  src/arch/psp/fileexp.o \
  src/arch/psp/gr_keyboard.o \
  src/arch/psp/gr_pointer.o \
  src/arch/psp/infowin.o \
  src/arch/psp/joy.o \
  src/arch/psp/kbd.o \
  src/arch/psp/menu.o \
  src/arch/psp/menudefs.o \
  src/arch/psp/mousedrv.o \
  src/arch/psp/osdmsg.o \
  src/arch/psp/pad.o \
  src/arch/psp/stubs.o \
  src/arch/psp/support.o \
  src/arch/psp/signals.o \
  src/arch/psp/ui.o \
  src/arch/psp/uiattach.o \
  src/arch/psp/uic64cart.o \
  src/arch/psp/uicmdline.o \
  src/arch/psp/uidrive.o \
  src/arch/psp/uimon.o \
  src/arch/psp/uiperipherial.o \
  src/arch/psp/uiprinter.o \
  src/arch/psp/uireu.o \
  src/arch/psp/uisid.o \
  src/arch/psp/uisnapshot.o \
  src/arch/psp/uisound.o \
  src/arch/psp/video.o \
  src/arch/psp/vkeyboard.o \
  src/arch/psp/vsidui.o \
  src/arch/psp/vsyncarch.o \
  src/arch/psp/PSPSpecific.o	\
  src/arch/psp/PSPFileSystem.o	\
  src/arch/psp/pspmain.o	\
  src/arch/psp/pspaudio.o	\
  src/arch/psp/PSPInputs.o	\
  src/arch/psp/PngImage.o	\
  src/arch/psp/ZipSupport.o	\
  src/arch/psp/unzip.o	\
	src/arch/psp/lib/lpng/png.o \
	src/arch/psp/lib/lpng/pngerror.o \
	src/arch/psp/lib/lpng/pngget.o \
	src/arch/psp/lib/lpng/pngmem.o \
	src/arch/psp/lib/lpng/pngpread.o \
	src/arch/psp/lib/lpng/pngread.o \
	src/arch/psp/lib/lpng/pngrio.o \
	src/arch/psp/lib/lpng/pngrtran.o \
	src/arch/psp/lib/lpng/pngrutil.o \
	src/arch/psp/lib/lpng/pngset.o \
	src/arch/psp/lib/lpng/pngtrans.o \
	src/arch/psp/lib/lpng/pngwio.o \
	src/arch/psp/lib/lpng/pngwrite.o \
	src/arch/psp/lib/lpng/pngwtran.o \
	src/arch/psp/lib/lpng/pngwutil.o \
	src/arch/psp/lib/zlib/adler32.o \
	src/arch/psp/lib/zlib/compress.o \
	src/arch/psp/lib/zlib/crc32.o \
	src/arch/psp/lib/zlib/deflate.o \
	src/arch/psp/lib/zlib/gzio.o \
	src/arch/psp/lib/zlib/infback.o \
	src/arch/psp/lib/zlib/inffast.o \
	src/arch/psp/lib/zlib/inflate.o \
	src/arch/psp/lib/zlib/inftrees.o \
	src/arch/psp/lib/zlib/trees.o \
	src/arch/psp/lib/zlib/uncompr.o \
	src/arch/psp/lib/zlib/zutil.o

#CFLAGS = -O3 -G0 -Wall -DPSP -ffast-math -floop-optimize2 -fbranch-target-load-optimize2 -ftree-vectorize -fno-inline-functions -fforce-addr -funroll-loops \
#Do not use, this is slower.
#CFLAGS = -O2 -G0 -Wall -DPSP \

LIBS = -lpspgum -lpspgu -lm -lgcc -lpspaudiolib -lpspaudio -lpsppower -lpng -lz -lzzip -lpsprtc \
	
CFLAGS = -O2 -G0 -Wall -DPSP \
  -include CommonHeader.h \
  -Isrc \
  -Isrc/arch/psp \
	-Isrc/arch/psp/lib/zlib \
	-Isrc/arch/psp/lib/lpng \
	-Isrc/arch \
	-Isrc/c64 \
	-Isrc/cbm-iisys \
	-Isrc/core \
	-Isrc/crtc \
	-Isrc/diskimage \
	-Isrc/drive \
	-Isrc/drivesys \
	-Isrc/fileio \
	-Isrc/fsdevice \
	-Isrc/gfxoutputdrv \
	-Isrc/iecbus \
	-Isrc/imagecontents \
	-Isrc/monitor \
	-Isrc/parallel \
	-Isrc/petsys \
	-Isrc/printerdrv \
	-Isrc/raster \
	-Isrc/rs232drv \
	-Isrc/serial \
	-Isrc/sid \
	-Isrc/sounddrv \
	-Isrc/tape \
	-Isrc/vdc \
	-Isrc/vdrive \
	-Isrc/vic20 \
	-Isrc/vicii \
	-Isrc/video
	
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

# USE_PSPSDK_LIBC = 1

PSP_EBOOT_ICON = ICON0.PNG 
PSP_EBOOT_PIC1 = Pic1.png 
EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = PSPVice

include $(PSPSDK)/lib/build.mak
