#include "vkeyboard.h"

extern BITMAP gr_keyboard;

static const int c64_keylen[] __attribute__((aligned(64))) = {
  L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL,
  L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_RETURN, L_CTRL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL,
  L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_CTRL, L_NORMAL, L_NORMAL, L_NORMAL,
  L_NORMAL, L_NORMAL, L_NORMAL, L_SPACE, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL,
  L_CTRL, L_FKEY, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_FKEY, L_NORMAL,
  L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_FKEY, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL, L_NORMAL,
  L_NORMAL, L_NORMAL, L_FKEY, L_CTRL, L_NORMAL
};

// Graphic Keyboard , key coordinates
// Code+Value
// Code are : C_YMINMAX, C_XPOS, C_KEYLEN, C_KEY
// L_xxx is lenght of key

static const int c64_maptable[] __attribute__((aligned(64))) = {
  
  // Row 1
  C_YMINMAX, 5, 5+14, C_XPOS, 7,
  C_KEYLEN, L_NORMAL, C_KEY, K_LEFTARROW, C_KEY, K_1, C_KEY, K_2, C_KEY, K_3, C_KEY, K_4, C_KEY, K_5, C_KEY, K_6, C_KEY, K_7, C_KEY, K_8, C_KEY, K_9, C_KEY, K_0, C_KEY, K_PLUS, C_KEY, K_MINUS, C_KEY, K_POUND, C_KEY, K_HOME, C_KEY, K_DEL, C_XPOS, 270, C_KEYLEN, L_FKEY, C_KEY, K_F1,

  // Row 2
  C_YMINMAX, 21, 21+14, C_XPOS, 7,
  C_KEYLEN, L_CTRL, C_KEY, K_CTRL, C_KEYLEN, L_NORMAL, C_KEY, K_Q, C_KEY, K_W, C_KEY, K_E, C_KEY, K_R, C_KEY, K_T, C_KEY, K_Y, C_KEY, K_U, C_KEY, K_I, C_KEY, K_O, C_KEY, K_P, C_KEY, K_AT, C_KEY, K_ASTERIX, C_KEY, K_UPARROW, C_KEYLEN, L_CTRL, C_KEY, K_RESTORE, C_XPOS, 270, C_KEYLEN, L_FKEY, C_KEY, K_F3,

  // Row 3
  C_YMINMAX, 37, 37+14, C_XPOS, 4,
  C_KEYLEN, L_NORMAL, C_KEY, K_STOP, C_KEY, K_SL, C_KEY, K_A, C_KEY, K_S, C_KEY, K_D, C_KEY, K_F, C_KEY, K_G, C_KEY, K_H, C_KEY, K_J, C_KEY, K_K, C_KEY, K_L, C_KEY, K_COLON, C_KEY, K_SEMICOLON, C_KEY, K_EQUAL, C_KEYLEN, L_RETURN, C_KEY, K_RETURN, C_XPOS, 270, C_KEYLEN, L_FKEY, C_KEY, K_F5,

  // Row 4
  C_YMINMAX, 53, 53+14, C_XPOS, 4,
  C_KEYLEN, L_NORMAL, C_KEY, K_CBM, C_KEYLEN, L_CTRL, C_KEY, K_LSHIFT, C_KEYLEN, L_NORMAL, C_KEY, K_Z, C_KEY, K_X, C_KEY, K_C, C_KEY, K_V, C_KEY, K_B, C_KEY, K_N, C_KEY, K_M, C_KEY, K_COMMA, C_KEY, K_DOT, C_KEY, K_SLASH, C_KEYLEN, L_CTRL, C_KEY, K_RSHIFT, C_KEYLEN, L_NORMAL, C_KEY, K_CRSRUPDOWN, C_KEY, K_CRSRLEFTRIGHT, C_XPOS, 270, C_KEYLEN, L_FKEY, C_KEY, K_F7,

  // Row 5
  C_YMINMAX, 69, 69+14, C_XPOS, 52,
  C_KEYLEN, L_SPACE, C_KEY, K_SPACE,

  C_END
};

void vkeyboard_set_c64()
{
  maptable = c64_maptable;
  keylen = c64_keylen;
  gr_curkbd = &gr_keyboard;
  kbd_numkeys = 66;
}
